const listData = [
  { country: "Afghanistan", code: "+93", iso: "AF", cca3: "AFG" },
  { country: "Albania", code: "+355", iso: "AL", cca3:"ALB" },
  { country: "Algeria", code: "+213", iso: "DZ" , cca3:"ALG"},
  { country: "American Samoa", code: "+1-684", iso: "AS" , cca3:"ASA"},
  { country: "Andorra", code: "+376", iso: "AD" , cca3:"AND"},
  { country: "Angola", code: "+244", iso: "AO" , cca3:"ANG"},
  { country: "Anguilla", code: "+1-264", iso: "AI" , cca3:"AIA"},
  { country: "Antarctica", code: "+672", iso: "AQ" , cca3:"ATA"},
  { country: "Antigua and Barbuda", code: "+1-268", iso: "AG" , cca3:"ATG"},
  { country: "Argentina", code: "+54", iso: "AR" , cca3:"ARG"},
  { country: "Armenia", code: "+374", iso: "AM" , cca3:"ARM"},
  { country: "Aruba", code: "+297", iso: "AW" , cca3:"ABW"},
  { country: "Australia", code: "+61", iso: "AU" , cca3:"AUS"},
  { country: "Austria", code: "+43", iso: "AT" , cca3:"AUT"},
  { country: "Azerbaijan", code: "+994", iso: "AZ" , cca3:"AZE"},
  { country: "Bahamas", code: "+1-242", iso: "BS" , cca3:"BHS"},
  { country: "Bahrain", code: "+973", iso: "BH" , cca3:"BHR"},
  { country: "Bangladesh", code: "+880", iso: "BD" , cca3:"BGD"},
  { country: "Barbados", code: "+1-246", iso: "BB" , cca3:"BRB"},
  { country: "Belarus", code: "+375", iso: "BY" , cca3:"BLR"},
  { country: "Belgium", code: "+32", iso: "BE" , cca3:"BEL"},
  { country: "Belize", code: "+501", iso: "BZ" , cca3:"BLZ"},
  { country: "Benin", code: "+229", iso: "BJ" , cca3:"BEN"},
  { country: "Bermuda", code: "+1-441", iso: "BM" , cca3:"BMU"},
  { country: "Bhutan", code: "+975", iso: "BT" , cca3:"BTN"},
  { country: "Bolivia", code: "+591", iso: "BO" , cca3:"BOL"},
  { country: "Bosnia and Herzegovina", code: "+387", iso: "BA" , cca3:"BIH"},
  { country: "Botswana", code: "+267", iso: "BW" , cca3:"BWA"},
  { country: "Brazil", code: "+55", iso: "BR" , cca3:"BRA"},
  { country: "British Indian Ocean Territory", code: "+246", iso: "IO" , cca3:"IOT"},
  { country: "British Virgin Islands", code: "+1-284", iso: "VG" , cca3:"VGB"},
  { country: "Brunei", code: "+673", iso: "BN" , cca3:"BRN"},
  { country: "Bulgaria", code: "+359", iso: "BG" , cca3:"BGR"},
  { country: "Burkina Faso", code: "+226", iso: "BF" , cca3:"BFA"},
  { country: "Burundi", code: "+257", iso: "BI" , cca3:"BDI"},
  { country: "Cambodia", code: "+855", iso: "KH" , cca3:"KHM"},
  { country: "Cameroon", code: "+237", iso: "CM" , cca3:"CMR"},
  { country: "Canada", code: "+1", iso: "CA" , cca3:"CAN"},
  { country: "Cape Verde", code: "+238", iso: "CV" , cca3:"CPV"},
  { country: "Cayman Islands", code: "+1-345", iso: "KY" , cca3:"CYM"},
  { country: "Central African Republic", code: "+236", iso: "CF" , cca3:"CAF"},
  { country: "Chad", code: "+235", iso: "TD" , cca3:"TCD"},
  { country: "Chile", code: "+56", iso: "CL" , cca3:"CHL"},
  { country: "China", code: "+86", iso: "CN" , cca3:"CHN"},
  { country: "Christmas Island", code: "+61", iso: "CX" , cca3:"CXR"},
  { country: "Cocos Islands", code: "+61", iso: "CC" , cca3:"CCK"},
  { country: "Colombia", code: "+57", iso: "CO" , cca3:"COL"},
  { country: "Comoros", code: "+269", iso: "KM" , cca3:"COM"},
  { country: "Cook Islands", code: "+682", iso: "CK" , cca3:"COK"},
  { country: "Costa Rica", code: "+506", iso: "CR" , cca3:"CRI"},
  { country: "Croatia", code: "+385", iso: "HR" , cca3:"HRV"},
  { country: "Cuba", code: "+53", iso: "CU" , cca3:"CUB"},
  { country: "Curacao", code: "+599", iso: "CW" , cca3:"CUW"},
  { country: "Cyprus", code: "+357", iso: "CY" , cca3:"CYP"},
  { country: "Czech Republic", code: "+420", iso: "CZ" , cca3:"CZE"},
  { country: "Democratic Republic of the Congo", code: "+243", iso: "CD" , cca3:"COD"},
  { country: "Denmark", code: "+45", iso: "DK" , cca3:"DNK"},
  { country: "Djibouti", code: "+253", iso: "DJ" , cca3:"DJI"},
  { country: "Dominica", code: "+1-767", iso: "DM" , cca3:"DOM"},
  { country: "Dominican Republic", code: "+1-809, 1-829, 1-849", iso: "DO" , cca3:"DOM"},
  { country: "East Timor", code: "+670", iso: "TL" , cca3:"TLS"},
  { country: "Ecuador", code: "+593", iso: "EC" , cca3:"ECU"},
  { country: "Egypt", code: "+20", iso: "EG" , cca3:"EGY"},
  { country: "El Salvador", code: "+503", iso: "SV" , cca3:"SLV"},
  { country: "Equatorial Guinea", code: "+240", iso: "GQ" , cca3:"GNQ"},
  { country: "Eritrea", code: "+291", iso: "ER" , cca3:"ERI"},
  { country: "Estonia", code: "+372", iso: "EE" , cca3:"EST"},
  { country: "Ethiopia", code: "+251", iso: "ET" , cca3:"ETH"},
  { country: "Falkland Islands", code: "+500", iso: "FK" , cca3:"FLK"},
  { country: "Faroe Islands", code: "+298", iso: "FO" , cca3:"FRO"},
  { country: "Fiji", code: "+679", iso: "FJ" , cca3:"FJI"},
  { country: "Finland", code: "+358", iso: "FI" , cca3:"FIN"},
  { country: "France", code: "+33", iso: "FR" , cca3:"FRA"},
  { country: "French Polynesia", code: "+689", iso: "PF" , cca3:"PYF"},
  { country: "Gabon", code: "+241", iso: "GA" , cca3:"GAB"},
  { country: "Gambia", code: "+220", iso: "GM" , cca3:"GMB"},
  { country: "Georgia", code: "+995", iso: "GE" , cca3:"GEO"},
  { country: "Germany", code: "+49", iso: "DE" , cca3:"DEU"},
  { country: "Ghana", code: "+233", iso: "GH" , cca3:"GHA"},
  { country: "Gibraltar", code: "+350", iso: "GI" , cca3:"GIB"},
  { country: "Greece", code: "+30", iso: "GR" , cca3:"GRC"},
  { country: "Greenland", code: "+299", iso: "GL" , cca3:"GRL"},
  { country: "Grenada", code: "+1-473", iso: "GD" , cca3:"GRD"},
  { country: "Guam", code: "+1-671", iso: "GU" , cca3:"GUM"},
  { country: "Guatemala", code: "+502", iso: "GT" , cca3:"GTM"},
  { country: "Guernsey", code: "+44-1481", iso: "GG" , cca3:"GGY"},
  { country: "Guinea", code: "+224", iso: "GN" , cca3:"GNQ"},
  { country: "Guinea-Bissau", code: "+245", iso: "GW" , cca3:"GNB"},
  { country: "Guyana", code: "+592", iso: "GY" , cca3:"GUF"},
  { country: "Haiti", code: "+509", iso: "HT" , cca3:"HTI"},
  { country: "Honduras", code: "+504", iso: "HN" , cca3:"HND"},
  { country: "Hong Kong", code: "+852", iso: "HK" , cca3:"HKG"},
  { country: "Hungary", code: "+36", iso: "HU" , cca3:"HUN"},
  { country: "Iceland", code: "+354", iso: "IS" , cca3:"ISL"},
  { country: "India", code: "+91", iso: "IN" , cca3:"IND"},
  { country: "Indonesia", code: "+62", iso: "ID" , cca3:"IDN"},
  { country: "Iran", code: "+98", iso: "IR" , cca3:"IRN"},
  { country: "Iraq", code: "+964", iso: "IQ" , cca3:"IRQ"},
  { country: "Ireland", code: "+353", iso: "IE" , cca3:"GBR"},
  { country: "Isle of Man", code: "+44-1624", iso: "IM" , cca3:"IMN"},
  { country: "Israel", code: "+972", iso: "IL" , cca3:"ISR"},
  { country: "Italy", code: "+39", iso: "IT" , cca3:"ITA"},
  { country: "Ivory Coast", code: "+225", iso: "CI" , cca3:"CIV"},
  { country: "Jamaica", code: "+1-876", iso: "JM" , cca3:"JAM"},
  { country: "Japan", code: "+81", iso: "JP" , cca3:"JPN"},
  { country: "Jersey", code: "+44-1534", iso: "JE" , cca3:"JEY"},
  { country: "Jordan", code: "+962", iso: "JO" , cca3:"JOR"},
  { country: "Kazakhstan", code: "+7", iso: "KZ" , cca3:"KAZ"},
  { country: "Kenya", code: "+254", iso: "KE" , cca3:"KEN"},
  { country: "Kiribati", code: "+686", iso: "KI" , cca3:"KIR"},
  { country: "Kosovo", code: "+383", iso: "XK" , cca3:"UNK"},
  { country: "Kuwait", code: "+965", iso: "KW" , cca3:"KWT"},
  { country: "Kyrgyzstan", code: "+996", iso: "KG" , cca3:"KGZ"},
  { country: "Laos", code: "+856", iso: "LA" , cca3:"LAO"},
  { country: "Latvia", code: "+371", iso: "LV" , cca3:"LVA"},
  { country: "Lebanon", code: "+961", iso: "LB" , cca3:"LBN"},
  { country: "Lesotho", code: "+266", iso: "LS" , cca3:"LSO"},
  { country: "Liberia", code: "+231", iso: "LR" , cca3:"LBR"},
  { country: "Libya", code: "+218", iso: "LY" , cca3:"LBY"},
  { country: "Liechtenstein", code: "+423", iso: "LI" , cca3:"LIE"},
  { country: "Lithuania", code: "+370", iso: "LT" , cca3:"LTU"},
  { country: "Luxembourg", code: "+352", iso: "LU" , cca3:"LUX"},
  { country: "Macao", code: "+853", iso: "MO" , cca3:"MAC"},
  { country: "Macedonia", code: "+389", iso: "MK" , cca3:"MKD"},
  { country: "Madagascar", code: "+261", iso: "MG" , cca3:"MDG"},
  { country: "Malawi", code: "+265", iso: "MW" , cca3:"MWI"},
  { country: "Malaysia", code: "+60", iso: "MY" , cca3:"MYS"},
  { country: "Maldives", code: "+960", iso: "MV" , cca3:"MDV"},
  { country: "Mali", code: "+223", iso: "ML" , cca3:"MLI"},
  { country: "Malta", code: "+356", iso: "MT" , cca3:"MLT"},
  { country: "Marshall Islands", code: "+692", iso: "MH" , cca3:"MHL"},
  { country: "Mauritania", code: "+222", iso: "MR" , cca3:"MRT"},
  { country: "Mauritius", code: "+230", iso: "MU" , cca3:"MUS"},
  { country: "Mayotte", code: "+262", iso: "YT" , cca3:"MYT"},
  { country: "Mexico", code: "+52", iso: "MX" , cca3:"MEX"},
  { country: "Micronesia", code: "+691", iso: "FM" , cca3:"FSM"},
  { country: "Moldova", code: "+373", iso: "MD" , cca3:"MDA"},
  { country: "Monaco", code: "+377", iso: "MC" , cca3:"MCO"},
  { country: "Mongolia", code: "+976", iso: "MN" , cca3:"MNG"},
  { country: "Montenegro", code: "+382", iso: "ME" , cca3:"MNE"},
  { country: "Montserrat", code: "+1-664", iso: "MS" , cca3:"MSR"},
  { country: "Morocco", code: "+212", iso: "MA" , cca3:"MAR"},
  { country: "Mozambique", code: "+258", iso: "MZ" , cca3:"MOZ"},
  { country: "Myanmar", code: "+95", iso: "MM" , cca3:"MMR"},
  { country: "Namibia", code: "+264", iso: "NA" , cca3:"NAM"},
  { country: "Nauru", code: "+674", iso: "NR" , cca3:"NRU"},
  { country: "Nepal", code: "+977", iso: "NP" , cca3:"NPL"},
  { country: "Netherlands", code: "+31", iso: "NL" , cca3:"NLD"},
  { country: "Netherlands Antilles", code: "+599", iso: "AN" , cca3:"NLD"},
  { country: "New Caledonia", code: "+687", iso: "NC" , cca3:"NCL"},
  { country: "New Zealand", code: "+64", iso: "NZ" , cca3:"NZL"},
  { country: "Nicaragua", code: "+505", iso: "NI" , cca3:"NIC"},
  { country: "Niger", code: "+227", iso: "NE" , cca3:"NER"},
  { country: "Nigeria", code: "+234", iso: "NG" , cca3:"NGA"},
  { country: "Niue", code: "+683", iso: "NU" , cca3:"NIU"},
  { country: "North Korea", code: "+850", iso: "KP" , cca3:"PRK"},
  { country: "Northern Mariana Islands", code: "+1-670", iso: "MP" , cca3:"MNP"},
  { country: "Norway", code: "+47", iso: "NO" , cca3:"NOR"},
  { country: "Oman", code: "+968", iso: "OM" , cca3:"OMN"},
  { country: "Pakistan", code: "+92", iso: "PK" , cca3:"PAK"},
  { country: "Palau", code: "+680", iso: "PW" , cca3:"PLW"},
  { country: "Palestine", code: "+970", iso: "PS" , cca3:"PSE"},
  { country: "Panama", code: "+507", iso: "PA" , cca3:"PAN"},
  { country: "Papua New Guinea", code: "+675", iso: "PG" , cca3:"PNG"},
  { country: "Paraguay", code: "+595", iso: "PY" , cca3:"PRY"},
  { country: "Peru", code: "+51", iso: "PE" , cca3:"PER"},
  { country: "Philippines", code: "+63", iso: "PH" , cca3:"PHL"},
  { country: "Pitcairn", code: "+64", iso: "PN" , cca3:"PCN"},
  { country: "Poland", code: "+48", iso: "PL" , cca3:"POL"},
  { country: "Portugal", code: "+351", iso: "PT" , cca3:"POR"},
  { country: "Puerto Rico", code: "+1-787, 1-939", iso: "PR" , cca3:"PRI"},
  { country: "Qatar", code: "+974", iso: "QA" , cca3:"QAT"},
  { country: "Republic of the Congo", code: "+242", iso: "CG" , cca3:"COG"},
  { country: "Reunion", code: "+262", iso: "RE" , cca3:"REU"},
  { country: "Romania", code: "+40", iso: "RO" , cca3:"ROU"},
  { country: "Russia", code: "+7", iso: "RU" , cca3:"RUS"},
  { country: "Rwanda", code: "+250", iso: "RW" , cca3:"RWA"},
  { country: "Saint Barthelemy", code: "+590", iso: "BL" , cca3:"BLM"},
  { country: "Saint Helena", code: "+290", iso: "SH" , cca3:"SHN"},
  { country: "Saint Kitts and Nevis", code: "+1-869", iso: "KN" , cca3:"KNA"},
  { country: "Saint Lucia", code: "+1-758", iso: "LC" , cca3:"LCA"},
  { country: "Saint Martin", code: "+590", iso: "MF" , cca3:"MAF"},
  { country: "Saint Pierre and Miquelon", code: "+508", iso: "PM" , cca3:"SPM"},
  { country: "Saint Vincent and the Grenadines", code: "+1-784", iso: "VC" , cca3:"VCT"},
  { country: "Samoa", code: "+685", iso: "WS" , cca3:"WSM"},
  { country: "San Marino", code: "+378", iso: "SM" , cca3:"SMR"},
  { country: "Sao Tome and Principe", code: "+239", iso: "ST" , cca3:"STP"},
  { country: "Saudi Arabia", code: "+966", iso: "SA" , cca3:"SAU"},
  { country: "Senegal", code: "+221", iso: "SN" , cca3:"SEN"},
  { country: "Serbia", code: "+381", iso: "RS" , cca3:"SRB"},
  { country: "Seychelles", code: "+248", iso: "SC" , cca3:"SYC"},
  { country: "Sierra Leone", code: "+232", iso: "SL" , cca3:"SLE"},
  { country: "Singapore", code: "+65", iso: "SG" , cca3:"SGP"},
  { country: "Sint Maarten", code: "+1-721", iso: "SX" , cca3:"SXM"},
  { country: "Slovakia", code: "+421", iso: "SK" , cca3:"SVK"},
  { country: "Slovenia", code: "+386", iso: "SI" , cca3:"SVN"},
  { country: "Solomon Islands", code: "+677", iso: "SB" , cca3:"SLB"},
  { country: "Somalia", code: "+252", iso: "SO" , cca3:"SOM"},
  { country: "South Africa", code: "+27", iso: "ZA" , cca3:"ZAF"},
  { country: "South Korea", code: "+82", iso: "KR" , cca3:"KOR"},
  { country: "South Sudan", code: "+211", iso: "SS" , cca3:"SSD"},
  { country: "Spain", code: "+34", iso: "ES" , cca3:"ESP"},
  { country: "Sri Lanka", code: "+94", iso: "LK" , cca3:"LKA"},
  { country: "Sudan", code: "+249", iso: "SD" , cca3:"SDN"},
  { country: "Suriname", code: "+597", iso: "SR" , cca3:"SUR"},
  { country: "Svalbard and Jan Mayen", code: "+47", iso: "SJ" , cca3:"SJM"},
  { country: "Swaziland", code: "+268", iso: "SZ" , cca3:"SWZ"},
  { country: "Sweden", code: "+46", iso: "SE" , cca3:"SWE"},
  { country: "Switzerland", code: "+41", iso: "CH" , cca3:"CHE"},
  { country: "Syria", code: "+963", iso: "SY" , cca3:"SYR"},
  { country: "Taiwan", code: "+886", iso: "TW" , cca3:"TWN"},
  { country: "Tajikistan", code: "+992", iso: "TJ" , cca3:"TJK"},
  { country: "Tanzania", code: "+255", iso: "TZ" , cca3:"TZA"},
  { country: "Thailand", code: "+66", iso: "TH" , cca3:"THA"},
  { country: "Togo", code: "+228", iso: "TG" , cca3:"TGO"},
  { country: "Tokelau", code: "+690", iso: "TK" , cca3:"TKL"},
  { country: "Tonga", code: "+676", iso: "TO" , cca3:"TON"},
  { country: "Trinidad and Tobago", code: "+1-868", iso: "TT" , cca3:"TTO"},
  { country: "Tunisia", code: "+216", iso: "TN" , cca3:"TUN"},
  { country: "Turkey", code: "+90", iso: "TR" , cca3:"TUR"},
  { country: "Turkmenistan", code: "+993", iso: "TM" , cca3:"TKM"},
  { country: "Turks and Caicos Islands", code: "+1-649", iso: "TC" , cca3:"TCA"},
  { country: "Tuvalu", code: "+688", iso: "TV" , cca3:"TUV"},
  { country: "U.S. Virgin Islands", code: "+1-340", iso: "VI" , cca3:"VIR"},
  { country: "Uganda", code: "+256", iso: "UG" , cca3:"UGA"},
  { country: "Ukraine", code: "+380", iso: "UA" , cca3:"UKR"},
  { country: "United Arab Emirates", code: "+971", iso: "AE" , cca3:"ARE"},
  { country: "United Kingdom", code: "+44", iso: "GB" , cca3:"GBR"},
  { country: "United States", code: " +1", iso: "US" , cca3:"USA"},
  { country: "Uruguay", code: "+598", iso: "UY" , cca3:"URY"},
  { country: "Uzbekistan", code: "+998", iso: "UZ" , cca3:"VUT"},
  { country: "Vanuatu", code: "+678", iso: "VU" , cca3:"VAT"},
  { country: "Vatican", code: "+379", iso: "VA" , cca3:"VAT"},
  { country: "Venezuela", code: "+58", iso: "VE" , cca3:"VEN"},
  { country: "Vietnam", code: "+84", iso: "VN" , cca3:"VNM"},
  { country: "Wallis and Futuna", code: "+681", iso: "WF" , cca3:"WLF"},
  { country: "Western Sahara", code: "+212", iso: "EH" , cca3:"ESH"},
  { country: "Yemen", code: "+967", iso: "YE" , cca3:"YEM"},
  { country: "Zambia", code: "+260", iso: "ZM" , cca3:"ZMB"},
  { country: "Zimbabwe", code: "+263", iso: "ZW" , cca3:"ZWE"},
];

export default listData;

export const countryInfo = [
  {
    name: "Afghanistan",
    code: "AF",
    capital: "Kabul",
    region: "AS",
    currency: {
      code: "AFN",
      name: "Afghan afghani",
      symbol: "؋",
    },
    language: {
      code: "ps",
      name: "Pashto",
    },
    flag: "https://flagcdn.com/h40/af.png",
    dialling_code: "+93",
    isoCode: "004",
  },
  {
    name: "Albania",
    code: "AL",
    capital: "Tirana",
    region: "EU",
    currency: {
      code: "ALL",
      name: "Albanian lek",
      symbol: "L",
    },
    language: {
      code: "sq",
      name: "Albanian",
    },
    flag: "https://flagcdn.com/h40/al.png",
    dialling_code: "+355",
    isoCode: "008",
  },
  {
    name: "Algeria",
    code: "DZ",
    capital: "Algiers",
    region: "AF",
    currency: {
      code: "DZD",
      name: "Algerian dinar",
      symbol: "د.ج",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/dz.png",
    dialling_code: "+213",
    isoCode: "012",
  },
  {
    name: "American Samoa",
    code: "US",
    capital: "Pago Pago",
    region: "OC",
    currency: {
      code: "USD",
      name: "United State Dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/us.png",
    dialling_code: "+1",
    isoCode: "016",
  },
  {
    name: "Andorra",
    code: "DE",
    capital: "Andorra la Vella",
    region: "EU",
    currency: {
      code: "EUR",
      name: "Euro",
      symbol: "€",
    },
    language: {
      code: "ca",
      name: "Catalan",
    },
    flag: "https://flagcdn.com/h40/de.png",
    dialling_code: "+376",
    isoCode: "020",
  },
  {
    name: "Angola",
    code: "AO",
    capital: "Luanda",
    region: "AF",
    currency: {
      code: "AOA",
      name: "Angolan kwanza",
      symbol: "Kz",
    },
    language: {
      code: "pt",
      name: "Portuguese",
    },
    flag: "https://flagcdn.com/h40/ag.png",
    dialling_code: "+244",
    isoCode: "024",
  },
  {
    name: "Anguilla",
    code: "AI",
    capital: "The Valley",
    region: "NA",
    currency: {
      code: "XCD",
      name: "East Caribbean dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/ai.png",
    dialling_code: "+43",
    isoCode: "660",
  },
  {
    name: "Argentina",
    code: "AR",
    capital: "Buenos Aires",
    region: "SA",
    currency: {
      code: "ARS",
      name: "Argentine peso",
      symbol: "$",
    },
    language: {
      code: "es",
      name: "Spanish",
    },
    flag: "https://flagcdn.com/h40/ar.png",
    dialling_code: "+54",
    isoCode: "032",
  },
  {
    name: "Armenia",
    code: "AM",
    capital: "Yerevan",
    region: "AS",
    currency: {
      code: "AMD",
      name: "Armenian dram",
      symbol: null,
    },
    language: {
      code: "hy",
      name: "Armenian",
    },
    flag: "https://flagcdn.com/h40/ar.png",
    dialling_code: "+374",
    isoCode: "051",
  },
  {
    name: "Aruba",
    code: "AW",
    capital: "Oranjestad",
    region: "SA",
    currency: {
      code: "AWG",
      name: "Aruban florin",
      symbol: "ƒ",
    },
    language: {
      code: "nl",
      name: "Dutch",
    },
    flag: "https://flagcdn.com/h40/aw.png",
    dialling_code: "+297",
    isoCode: "533",
  },
  {
    name: "Australia",
    code: "AU",
    capital: "Canberra",
    region: "OC",
    currency: {
      code: "AUD",
      name: "Australian dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/au.png",
    dialling_code: "+61",
    isoCode: "036",
  },
  {
    name: "Azerbaijan",
    code: "AZ",
    capital: "Baku",
    region: "AS",
    currency: {
      code: "AZN",
      name: "Azerbaijani manat",
      symbol: null,
    },
    language: {
      code: "az",
      name: "Azerbaijani",
    },
    flag: "https://flagcdn.com/h40/az.png",
    dialling_code: "+994",
    isoCode: "031",
  },
  {
    name: "Bahamas",
    code: "BS",
    capital: "Nassau",
    region: "NA",
    currency: {
      code: "BSD",
      name: "Bahamian dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/bh.png",
    dialling_code: "+1",
    isoCode: "044",
  },
  {
    name: "Bahrain",
    code: "BH",
    capital: "Manama",
    region: "AS",
    currency: {
      code: "BHD",
      name: "Bahraini dinar",
      symbol: ".د.ب",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/bh.png",
    dialling_code: "+973",
    isoCode: "048",
  },
  {
    name: "Bangladesh",
    code: "BD",
    capital: "Dhaka",
    region: "AS",
    currency: {
      code: "BDT",
      name: "Bangladeshi taka",
      symbol: "৳",
    },
    language: {
      code: "bn",
      name: "Bengali",
    },
    flag: "https://flagcdn.com/h40/bg.png",
    dialling_code: "+880",
    isoCode: "050",
  },
  {
    name: "Barbados",
    code: "BB",
    capital: "Bridgetown",
    region: "NA",
    currency: {
      code: "BBD",
      name: "Barbadian dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/br.png",
    dialling_code: "+1",
    isoCode: "052",
  },
  {
    name: "Belarus",
    code: "BY",
    capital: "Minsk",
    region: "EU",
    currency: {
      code: "BYN",
      name: "New Belarusian ruble",
      symbol: "Br",
    },
    language: {
      code: "be",
      name: "Belarusian",
    },
    flag: "https://flagcdn.com/h40/bl.png",
    dialling_code: "+375",
    isoCode: "112",
  },
  {
    name: "Belize",
    code: "BZ",
    capital: "Belmopan",
    region: "NA",
    currency: {
      code: "BZD",
      name: "Belize dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/bl.png",
    dialling_code: "+501",
    isoCode: "084",
  },
  {
    name: "Benin",
    code: "BJ",
    capital: "Porto-Novo",
    region: "AF",
    currency: {
      code: "XOF",
      name: "West African CFA franc",
      symbol: "Fr",
    },
    language: {
      code: "fr",
      name: "French",
    },
    flag: "https://flagcdn.com/h40/be.png",
    dialling_code: "+229",
    isoCode: "204",
  },
  {
    name: "Bermuda",
    code: "BM",
    capital: "Hamilton",
    region: "NA",
    currency: {
      code: "BMD",
      name: "Bermudian dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/bm.png",
    dialling_code: "+1",
    isoCode: "060",
  },
  {
    name: "Bhutan",
    code: "BT",
    capital: "Thimphu",
    region: "AS",
    currency: {
      code: "BTN",
      name: "Bhutanese ngultrum",
      symbol: "Nu.",
    },
    language: {
      code: "dz",
      name: "Dzongkha",
    },
    flag: "https://flagcdn.com/h40/bt.png",
    dialling_code: "+975",
    isoCode: "064",
  },
  {
    name: "Bolivia (Plurinational State of)",
    code: "BO",
    capital: "Sucre",
    region: "SA",
    currency: {
      code: "BOB",
      name: "Bolivian boliviano",
      symbol: "Bs.",
    },
    language: {
      code: "es",
      name: "Spanish",
    },
    flag: "https://flagcdn.com/h40/bo.png",
    dialling_code: "+591",
    isoCode: "068",
  },
  {
    name: "Bosnia and Herzegovina",
    code: "BA",
    capital: "Sarajevo",
    region: "EU",
    currency: {
      code: "BAM",
      name: "Bosnia and Herzegovina convertible mark",
      symbol: null,
    },
    language: {
      code: "bs",
      name: "Bosnian",
    },
    flag: "https://flagcdn.com/h40/bi.png",
    dialling_code: "+387",
    isoCode: "070",
  },
  {
    name: "Botswana",
    code: "BW",
    capital: "Gaborone",
    region: "AF",
    currency: {
      code: "BWP",
      name: "Botswana pula",
      symbol: "P",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/bw.png",
    dialling_code: "+267",
    isoCode: "072",
  },
  {
    name: "Brazil",
    code: "BR",
    capital: "Brasília",
    region: "SA",
    currency: {
      code: "BRL",
      name: "Brazilian real",
      symbol: "R$",
    },
    language: {
      code: "pt",
      name: "Portuguese",
    },
    flag: "https://flagcdn.com/h40/br.png",
    dialling_code: "+55",
    isoCode: "076",
  },
  {
    name: "Brunei Darussalam",
    code: "BN",
    capital: "Bandar Seri Begawan",
    region: "AS",
    currency: {
      code: "BND",
      name: "Brunei dollar",
      symbol: "$",
    },
    language: {
      code: "ms",
      name: "Malay",
    },
    flag: "https://flagcdn.com/h40/br.png",
    dialling_code: "+673",
    isoCode: "096",
  },
  {
    name: "Bulgaria",
    code: "BG",
    capital: "Sofia",
    region: "EU",
    currency: {
      code: "BGN",
      name: "Bulgarian lev",
      symbol: "лв",
    },
    language: {
      code: "bg",
      name: "Bulgarian",
    },
    flag: "https://flagcdn.com/h40/bg.png",
    dialling_code: "+359",
    isoCode: "100",
  },
  {
    name: "Burundi",
    code: "BI",
    capital: "Bujumbura",
    region: "AF",
    currency: {
      code: "BIF",
      name: "Burundian franc",
      symbol: "Fr",
    },
    language: {
      code: "fr",
      name: "French",
    },
    flag: "https://flagcdn.com/h40/bd.png",
    dialling_code: "+257",
    isoCode: "108",
  },
  {
    name: "Cambodia",
    code: "KH",
    capital: "Phnom Penh",
    region: "AS",
    currency: {
      code: "KHR",
      name: "Cambodian riel",
      symbol: "៛",
    },
    language: {
      code: "km",
      name: "Khmer",
    },
    flag: "https://flagcdn.com/h40/kh.png",
    dialling_code: "+855",
    isoCode: "116",
  },
  {
    name: "Cameroon",
    code: "CM",
    capital: "Yaoundé",
    region: "AF",
    currency: {
      code: "XAF",
      name: "Central African CFA franc",
      symbol: "Fr",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/cm.png",
    dialling_code: "+237",
    isoCode: "120",
  },
  {
    name: "Canada",
    code: "CA",
    capital: "Ottawa",
    region: "NA",
    currency: {
      code: "CAD",
      name: "Canadian dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/ca.png",
    dialling_code: "+1",
    isoCode: "124",
  },
  {
    name: "Cabo Verde",
    code: "CV",
    capital: "Praia",
    region: "AF",
    currency: {
      code: "CVE",
      name: "Cape Verdean escudo",
      symbol: "Esc",
    },
    language: {
      code: "pt",
      iso639_2: "por",
      name: "Portuguese",
      nativeName: "Português",
    },
    flag: "https://flagcdn.com/h40/cp.png",
    dialling_code: "+238",
    isoCode: "132",
  },
  {
    name: "Cayman Islands",
    code: "KY",
    capital: "George Town",
    region: "NA",
    demonym: "Caymanian",
    currency: {
      code: "KYD",
      name: "Cayman Islands dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/cy.png",
    dialling_code: "+1",
    isoCode: "136",
  },
  {
    name: "Chile",
    code: "CL",
    capital: "Santiago",
    region: "SA",
    currency: {
      code: "CLP",
      name: "Chilean peso",
      symbol: "$",
    },
    language: {
      code: "es",
      iso639_2: "spa",
      name: "Spanish",
      nativeName: "Español",
    },
    flag: "https://flagcdn.com/h40/ch.png",
    dialling_code: "+56",
    isoCode: "152",
  },
  {
    name: "China",
    code: "CN",
    capital: "Beijing",
    region: "AS",
    currency: {
      code: "CNY",
      name: "Chinese yuan",
      symbol: "¥",
    },
    language: {
      code: "zh",
      name: "Chinese",
    },
    flag: "https://flagcdn.com/h40/ch.png",
    dialling_code: "+86",
    isoCode: "156",
  },
  {
    name: "Colombia",
    code: "CO",
    capital: "Bogotá",
    region: "SA",
    currency: {
      code: "COP",
      name: "Colombian peso",
      symbol: "$",
    },
    language: {
      code: "es",
      name: "Spanish",
    },
    flag: "https://flagcdn.com/h40/co.png",
    dialling_code: "+57",
    isoCode: "170",
  },
  {
    name: "Comoros",
    code: "KM",
    capital: "Moroni",
    region: "AF",
    currency: {
      code: "KMF",
      name: "Comorian franc",
      symbol: "Fr",
    },
    language: {
      code: "fr",
      name: "French",
    },
    flag: "https://flagcdn.com/h40/co.png",
    dialling_code: "+269",
    isoCode: "174",
  },
  {
    name: "Congo (Democratic Republic of the)",
    code: "CD",
    capital: "Kinshasa",
    region: "AF",
    currency: {
      code: "CDF",
      name: "Congolese franc",
      symbol: "Fr",
    },
    language: {
      code: "fr",
      name: "French",
    },
    flag: "https://flagcdn.com/h40/co.png",
    dialling_code: "+243",
    isoCode: "180",
  },
  {
    name: "Cook Islands",
    code: "CK",
    capital: "Avarua",
    region: "OC",
    currency: {
      code: "NZD",
      name: "New Zealand dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/co.png",
    dialling_code: "+682",
    isoCode: "184",
  },
  {
    name: "Costa Rica",
    code: "CR",
    capital: "San José",
    region: "NA",
    currency: {
      code: "CRC",
      name: "Costa Rican colón",
      symbol: "₡",
    },
    language: {
      code: "es",
      name: "Spanish",
    },
    flag: "https://flagcdn.com/h40/cr.png",
    dialling_code: "+506",
    isoCode: "188",
  },
  {
    name: "Croatia",
    code: "HR",
    capital: "Zagreb",
    region: "EU",
    currency: {
      code: "HRK",
      name: "Croatian kuna",
      symbol: "kn",
    },
    language: {
      code: "hr",
      name: "Croatian",
    },
    flag: "https://flagcdn.com/h40/hr.png",
    dialling_code: "+385",
    isoCode: "191",
  },
  {
    name: "Cuba",
    code: "CU",
    capital: "Havana",
    region: "NA",
    currency: {
      code: "CUC",
      name: "Cuban convertible peso",
      symbol: "$",
    },
    language: {
      code: "es",
      name: "Spanish",
    },
    flag: "https://flagcdn.com/h40/cu.png",
    dialling_code: "+53",
    isoCode: "192",
  },
  {
    name: "Czech Republic",
    code: "CZ",
    capital: "Prague",
    region: "EU",
    currency: {
      code: "CZK",
      name: "Czech koruna",
      symbol: "Kč",
    },
    language: {
      code: "cs",
      name: "Czech",
    },
    flag: "https://flagcdn.com/h40/cz.png",
    dialling_code: "+420",
    isoCode: "203",
  },
  {
    name: "Denmark",
    code: "DK",
    capital: "Copenhagen",
    region: "EU",
    currency: {
      code: "DKK",
      name: "Danish krone",
      symbol: "kr",
    },
    language: {
      code: "da",
      name: "Danish",
    },
    flag: "https://flagcdn.com/h40/dk.png",
    dialling_code: "+45",
    isoCode: "208",
  },
  {
    name: "Djibouti",
    code: "DJ",
    capital: "Djibouti",
    region: "AF",
    currency: {
      code: "DJF",
      name: "Djiboutian franc",
      symbol: "Fr",
    },
    language: {
      code: "fr",
      name: "French",
    },
    flag: "https://flagcdn.com/h40/dj.png",
    dialling_code: "+253",
    isoCode: "262",
  },
  {
    name: "Dominican Republic",
    code: "DO",
    capital: "Santo Domingo",
    region: "NA",
    currency: {
      code: "DOP",
      name: "Dominican peso",
      symbol: "$",
    },
    language: {
      code: "es",
      name: "Spanish",
    },
    flag: "https://flagcdn.com/h40/do.png",
    dialling_code: "+1",
    isoCode: "214",
  },
  {
    name: "Egypt",
    code: "EG",
    capital: "Cairo",
    region: "AF",
    currency: {
      code: "EGP",
      name: "Egyptian pound",
      symbol: "£",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/eg.png",
    dialling_code: "+20",
    isoCode: "818",
  },
  {
    name: "Eritrea",
    code: "ER",
    capital: "Asmara",
    region: "AF",
    currency: {
      code: "ERN",
      name: "Eritrean nakfa",
      symbol: "Nfk",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/er.png",
    dialling_code: "+291",
    isoCode: "232",
  },
  {
    name: "Ethiopia",
    code: "ET",
    capital: "Addis Ababa",
    region: "AF",
    currency: {
      code: "ETB",
      name: "Ethiopian birr",
      symbol: "Br",
    },
    language: {
      code: "am",
      name: "Amharic",
    },
    flag: "https://flagcdn.com/h40/et.png",
    dialling_code: "+251",
    isoCode: "231",
  },
  {
    name: "Falkland Islands (Malvinas)",
    code: "FK",
    capital: "Stanley",
    region: "SA",
    currency: {
      code: "FKP",
      name: "Falkland Islands pound",
      symbol: "£",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/fk.png",
    dialling_code: "+500",
    isoCode: "238",
  },
  {
    name: "Fiji",
    code: "FJ",
    capital: "Suva",
    region: "OC",
    currency: {
      code: "FJD",
      name: "Fijian dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/fj.png",
    dialling_code: "+679",
    isoCode: "242",
  },
  {
    name: "French Polynesia",
    code: "PF",
    capital: "Papeetē",
    region: "OC",
    currency: {
      code: "XPF",
      name: "CFP franc",
      symbol: "Fr",
    },
    language: {
      code: "fr",
      name: "French",
    },
    flag: "https://flagcdn.com/h40/py.png",
    dialling_code: "+689",
    isoCode: "258",
  },
  {
    name: "Gambia",
    code: "GM",
    capital: "Banjul",
    region: "AF",
    currency: {
      code: "GMD",
      name: "Gambian dalasi",
      symbol: "D",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/gm.png",
    dialling_code: "+220",
    isoCode: "270",
  },
  {
    name: "Georgia",
    code: "GE",
    capital: "Tbilisi",
    region: "AS",
    currency: {
      code: "GEL",
      name: "Georgian Lari",
      symbol: "ლ",
    },
    language: {
      code: "ka",
      name: "Georgian",
    },
    flag: "https://flagcdn.com/h40/ge.png",
    dialling_code: "+995",
    isoCode: "268",
  },
  {
    name: "Ghana",
    code: "GH",
    capital: "Accra",
    region: "AF",
    currency: {
      code: "GHS",
      name: "Ghanaian cedi",
      symbol: "₵",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/gh.png",
    dialling_code: "+233",
    isoCode: "288",
  },
  {
    name: "Gibraltar",
    code: "GI",
    capital: "Gibraltar",
    region: "EU",
    currency: {
      code: "GIP",
      name: "Gibraltar pound",
      symbol: "£",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/gi.png",
    dialling_code: "+350",
    isoCode: "292",
  },
  {
    name: "Guatemala",
    code: "GT",
    capital: "Guatemala City",
    region: "NA",
    currency: {
      code: "GTQ",
      name: "Guatemalan quetzal",
      symbol: "Q",
    },
    language: {
      code: "es",
      name: "Spanish",
    },
    flag: "https://flagcdn.com/h40/gt.png",
    dialling_code: "+502",
    isoCode: "320",
  },
  {
    name: "Guinea",
    code: "GN",
    capital: "Conakry",
    region: "AF",
    currency: {
      code: "GNF",
      name: "Guinean franc",
      symbol: "Fr",
    },
    language: {
      code: "fr",
      name: "French",
    },
    flag: "https://flagcdn.com/h40/gi.png",
    dialling_code: "+224",
    isoCode: "324",
  },
  {
    name: "Guyana",
    code: "GY",
    capital: "Georgetown",
    region: "SA",
    currency: {
      code: "GYD",
      name: "Guyanese dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/gu.png",
    dialling_code: "+592",
    isoCode: "328",
  },
  {
    name: "Haiti",
    code: "HT",
    capital: "Port-au-Prince",
    region: "Americas",
    currency: {
      code: "HTG",
      name: "Haitian gourde",
      symbol: "G",
    },
    language: {
      code: "fr",
      name: "French",
    },
    flag: "https://flagcdn.com/h40/ht.png",
    dialling_code: "+509",
    isoCode: "332",
  },
  {
    name: "Honduras",
    code: "HN",
    capital: "Tegucigalpa",
    region: "NA",
    currency: {
      code: "HNL",
      name: "Honduran lempira",
      symbol: "L",
    },
    language: {
      code: "es",
      name: "Spanish",
    },
    flag: "https://flagcdn.com/h40/hn.png",
    dialling_code: "+504",
    isoCode: "340",
  },
  {
    name: "Hong Kong",
    code: "HK",
    capital: "City of Victoria",
    region: "AS",
    currency: {
      code: "HKD",
      name: "Hong Kong dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/hk.png",
    dialling_code: "+852",
    isoCode: "344",
  },
  {
    name: "Hungary",
    code: "HU",
    capital: "Budapest",
    region: "EU",
    currency: {
      code: "HUF",
      name: "Hungarian forint",
      symbol: "Ft",
    },
    language: {
      code: "hu",
      name: "Hungarian",
    },
    flag: "https://flagcdn.com/h40/hu.png",
    dialling_code: "+36",
    isoCode: "348",
  },
  {
    name: "Iceland",
    code: "IS",
    capital: "Reykjavík",
    region: "EU",
    currency: {
      code: "ISK",
      name: "Icelandic króna",
      symbol: "kr",
    },
    language: {
      code: "is",
      name: "Icelandic",
    },
    flag: "https://flagcdn.com/h40/is.png",
    dialling_code: "+354",
    isoCode: "352",
  },
  {
    name: "India",
    code: "IN",
    capital: "New Delhi",
    region: "AS",
    currency: {
      code: "INR",
      name: "Indian rupee",
      symbol: "₹",
    },
    language: {
      code: "hi",
      name: "Hindi",
    },
    flag: "https://flagcdn.com/h40/in.png",
    dialling_code: "+91",
    isoCode: "356",
  },
  {
    name: "Indonesia",
    code: "ID",
    capital: "Jakarta",
    region: "AS",
    currency: {
      code: "IDR",
      name: "Indonesian rupiah",
      symbol: "Rp",
    },
    language: {
      code: "id",
      name: "Indonesian",
    },
    flag: "https://flagcdn.com/h40/id.png",
    dialling_code: "+62",
    isoCode: "360",
  },
  {
    name: "Iran (Islamic Republic of)",
    code: "IR",
    capital: "Tehran",
    region: "AS",
    currency: {
      code: "IRR",
      name: "Iranian rial",
      symbol: "﷼",
    },
    language: {
      code: "fa",
      name: "Persian (Farsi)",
    },
    flag: "https://flagcdn.com/h40/ir.png",
    dialling_code: "+98",
    isoCode: "364",
  },
  {
    name: "Iraq",
    code: "IQ",
    capital: "Baghdad",
    region: "AS",
    currency: {
      code: "IQD",
      name: "Iraqi dinar",
      symbol: "ع.د",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/ir.png",
    dialling_code: "+964",
    isoCode: "368",
  },
  {
    name: "Israel",
    code: "IL",
    capital: "Jerusalem",
    region: "AS",
    currency: {
      code: "ILS",
      name: "Israeli new shekel",
      symbol: "₪",
    },
    language: {
      code: "he",
      name: "Hebrew (modern)",
    },
    flag: "https://flagcdn.com/h40/is.png",
    dialling_code: "+972",
    isoCode: "376",
  },
  {
    name: "Jamaica",
    code: "JM",
    capital: "Kingston",
    region: "NA",
    currency: {
      code: "JMD",
      name: "Jamaican dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/jm.png",
    dialling_code: "+1",
    isoCode: "388",
  },
  {
    name: "Japan",
    code: "JP",
    capital: "Tokyo",
    region: "AS",
    currency: {
      code: "JPY",
      name: "Japanese yen",
      symbol: "¥",
    },
    language: {
      code: "ja",
      name: "Japanese",
    },
    flag: "https://flagcdn.com/h40/jp.png",
    dialling_code: "+81",
    isoCode: "392",
  },
  {
    name: "Jordan",
    code: "JO",
    capital: "Amman",
    region: "AS",
    currency: {
      code: "JOD",
      name: "Jordanian dinar",
      symbol: "د.ا",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/jo.png",
    dialling_code: "+962",
    isoCode: "400",
  },
  {
    name: "Kazakhstan",
    code: "KZ",
    capital: "Astana",
    region: "AS",
    currency: {
      code: "KZT",
      name: "Kazakhstani tenge",
      symbol: null,
    },
    language: {
      code: "kk",
      name: "Kazakh",
    },
    flag: "https://flagcdn.com/h40/kz.png",
    dialling_code: "+7",
    isoCode: "398",
  },
  {
    name: "Kenya",
    code: "KE",
    capital: "Nairobi",
    region: "AF",
    currency: {
      code: "KES",
      name: "Kenyan shilling",
      symbol: "Sh",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/ke.png",
    dialling_code: "+254",
    isoCode: "404",
  },
  {
    name: "Kuwait",
    code: "KW",
    capital: "Kuwait City",
    region: "AS",
    currency: {
      code: "KWD",
      name: "Kuwaiti dinar",
      symbol: "د.ك",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/kw.png",
    dialling_code: "+965",
    isoCode: "414",
  },
  {
    name: "Kyrgyzstan",
    code: "KG",
    capital: "Bishkek",
    region: "AS",
    currency: {
      code: "KGS",
      name: "Kyrgyzstani som",
      symbol: "с",
    },
    language: {
      code: "ky",
      name: "Kyrgyz",
    },
    flag: "https://flagcdn.com/h40/kg.png",
    dialling_code: "+996",
    isoCode: "417",
  },
  {
    name: "Lao People's Democratic Republic",
    code: "LA",
    capital: "Vientiane",
    region: "AS",
    currency: {
      code: "LAK",
      name: "Lao kip",
      symbol: "₭",
    },
    language: {
      code: "lo",
      name: "Lao",
    },
    flag: "https://flagcdn.com/h40/la.png",
    dialling_code: "+856",
    isoCode: "418",
  },
  {
    name: "Lebanon",
    code: "LB",
    capital: "Beirut",
    region: "AS",
    currency: {
      code: "LBP",
      name: "Lebanese pound",
      symbol: "ل.ل",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/lb.png",
    dialling_code: "+961",
    isoCode: "422",
  },
  {
    name: "Lesotho",
    code: "LS",
    capital: "Maseru",
    region: "AF",
    currency: {
      code: "LSL",
      name: "Lesotho loti",
      symbol: "L",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/ls.png",
    dialling_code: "+266",
    isoCode: "426",
  },
  {
    name: "Liberia",
    code: "LR",
    capital: "Monrovia",
    region: "AF",
    currency: {
      code: "LRD",
      name: "Liberian dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/lb.png",
    dialling_code: "+231",
    isoCode: "430",
  },
  {
    name: "Libya",
    code: "LY",
    capital: "Tripoli",
    region: "AF",
    currency: {
      code: "LYD",
      name: "Libyan dinar",
      symbol: "ل.د",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/lb.png",
    dialling_code: "+218",
    isoCode: "434",
  },
  {
    name: "Liechtenstein",
    code: "LI",
    capital: "Vaduz",
    region: "EU",
    currency: {
      code: "CHF",
      name: "Swiss franc",
      symbol: "Fr",
    },
    language: {
      code: "de",
      name: "German",
    },
    flag: "https://flagcdn.com/h40/li.png",
    dialling_code: "+423",
    isoCode: "438",
  },
  {
    name: "Macao",
    code: "MO",
    capital: "",
    region: "AS",
    currency: {
      code: "MOP",
      name: "Macanese pataca",
      symbol: "P",
    },
    language: {
      code: "zh",
      name: "Chinese",
    },
    flag: "https://flagcdn.com/h40/ma.png",
    dialling_code: "+853",
    isoCode: "446",
  },
  {
    name: "Macedonia (the former Yugoslav Republic of)",
    code: "MK",
    capital: "Skopje",
    region: "EU",
    currency: {
      code: "MKD",
      name: "Macedonian denar",
      symbol: "ден",
    },
    language: {
      code: "mk",
      name: "Macedonian",
    },
    flag: "https://flagcdn.com/h40/mk.png",
    dialling_code: "+389",
    isoCode: "807",
  },
  {
    name: "Madagascar",
    code: "MG",
    capital: "Antananarivo",
    region: "AF",
    currency: {
      code: "MGA",
      name: "Malagasy ariary",
      symbol: "Ar",
    },
    language: {
      code: "fr",
      name: "French",
    },
    flag: "https://flagcdn.com/h40/md.png",
    dialling_code: "+261",
    isoCode: "450",
  },
  {
    name: "Malawi",
    code: "MW",
    capital: "Lilongwe",
    region: "AF",
    currency: {
      code: "MWK",
      name: "Malawian kwacha",
      symbol: "MK",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/mw.png",
    dialling_code: "+265",
    isoCode: "454",
  },
  {
    name: "Malaysia",
    code: "MY",
    capital: "Kuala Lumpur",
    region: "AS",
    currency: {
      code: "MYR",
      name: "Malaysian ringgit",
      symbol: "RM",
    },
    language: {
      code: null,
      name: "Malaysian",
    },
    flag: "https://flagcdn.com/h40/my.png",
    dialling_code: "+60",
    isoCode: "458",
  },
  {
    name: "Maldives",
    code: "MV",
    capital: "Malé",
    region: "AS",
    currency: {
      code: "MVR",
      name: "Maldivian rufiyaa",
      symbol: ".ރ",
    },
    language: {
      code: "dv",
      name: "Divehi",
    },
    flag: "https://flagcdn.com/h40/md.png",
    dialling_code: "+960",
    isoCode: "462",
  },
  {
    name: "Mauritania",
    code: "MR",
    capital: "Nouakchott",
    region: "AF",
    currency: {
      code: "MRO",
      name: "Mauritanian ouguiya",
      symbol: "UM",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/mr.png",
    dialling_code: "+222",
    isoCode: "478",
  },
  {
    name: "Mauritius",
    code: "MU",
    capital: "Port Louis",
    region: "AF",
    currency: {
      code: "MUR",
      name: "Mauritian rupee",
      symbol: "₨",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/mu.png",
    dialling_code: "+230",
    isoCode: "480",
  },
  {
    name: "Mexico",
    code: "MX",
    capital: "Mexico City",
    region: "NA",
    currency: {
      code: "MXN",
      name: "Mexican peso",
      symbol: "$",
    },
    language: {
      code: "es",
      name: "Spanish",
    },
    flag: "https://flagcdn.com/h40/me.png",
    dialling_code: "+52",
    isoCode: "484",
  },
  {
    name: "Moldova (Republic of)",
    code: "MD",
    capital: "Chișinău",
    region: "EU",
    currency: {
      code: "MDL",
      name: "Moldovan leu",
      symbol: "L",
    },
    language: {
      code: "ro",
      name: "Romanian",
    },
    flag: "https://flagcdn.com/h40/md.png",
    dialling_code: "+373",
    isoCode: "498",
  },
  {
    name: "Mongolia",
    code: "MN",
    capital: "Ulan Bator",
    region: "AS",
    currency: {
      code: "MNT",
      name: "Mongolian tögrög",
      symbol: "₮",
    },
    language: {
      code: "mn",
      name: "Mongolian",
    },
    flag: "https://flagcdn.com/h40/mn.png",
    dialling_code: "+976",
    isoCode: "496",
  },
  {
    name: "Morocco",
    code: "MA",
    capital: "Rabat",
    region: "AF",
    currency: {
      code: "MAD",
      name: "Moroccan dirham",
      symbol: "د.م.",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/ma.png",
    dialling_code: "+212",
    isoCode: "504",
  },
  {
    name: "Mozambique",
    code: "MZ",
    capital: "Maputo",
    region: "AF",
    currency: {
      code: "MZN",
      name: "Mozambican metical",
      symbol: "MT",
    },
    language: {
      code: "pt",
      name: "Portuguese",
    },
    flag: "https://flagcdn.com/h40/mo.png",
    dialling_code: "+258",
    isoCode: "508",
  },
  {
    name: "Myanmar",
    code: "MM",
    capital: "Naypyidaw",
    region: "AS",
    currency: {
      code: "MMK",
      name: "Burmese kyat",
      symbol: "Ks",
    },
    language: {
      code: "my",
      name: "Burmese",
    },
    flag: "https://flagcdn.com/h40/mm.png",
    dialling_code: "+95",
    isoCode: "104",
  },
  {
    name: "Namibia",
    code: "NA",
    capital: "Windhoek",
    region: "AF",
    currency: {
      code: "NAD",
      name: "Namibian dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/na.png",
    dialling_code: "+264",
    isoCode: "516",
  },
  {
    name: "Nepal",
    code: "NP",
    capital: "Kathmandu",
    region: "AS",
    currency: {
      code: "NPR",
      name: "Nepalese rupee",
      symbol: "₨",
    },
    language: {
      code: "ne",
      name: "Nepali",
    },
    flag: "https://flagcdn.com/h40/np.png",
    dialling_code: "+977",
    isoCode: "524",
  },
  {
    name: "Nicaragua",
    code: "NI",
    capital: "Managua",
    region: "NA",
    currency: {
      code: "NIO",
      name: "Nicaraguan córdoba",
      symbol: "C$",
    },
    language: {
      code: "es",
      name: "Spanish",
    },
    flag: "https://flagcdn.com/h40/ni.png",
    dialling_code: "+505",
    isoCode: "558",
  },
  {
    name: "Nigeria",
    code: "NG",
    capital: "Abuja",
    region: "AF",
    currency: {
      code: "NGN",
      name: "Nigerian naira",
      symbol: "₦",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/ng.png",
    dialling_code: "+234",
    isoCode: "566",
  },
  {
    name: "Korea (Democratic People's Republic of)",
    code: "KP",
    capital: "Pyongyang",
    region: "AS",
    currency: {
      code: "KPW",
      name: "North Korean won",
      symbol: "₩",
    },
    language: {
      code: "ko",
      name: "Korean",
    },
    flag: "https://flagcdn.com/h40/pr.png",
    dialling_code: "+850",
    isoCode: "408",
  },
  {
    name: "Norway",
    code: "NO",
    capital: "Oslo",
    region: "EU",
    currency: {
      code: "NOK",
      name: "Norwegian krone",
      symbol: "kr",
    },
    language: {
      code: "no",
      name: "Norwegian",
    },
    flag: "https://flagcdn.com/h40/no.png",
    dialling_code: "+47",
    isoCode: "578",
  },
  {
    name: "Oman",
    code: "OM",
    capital: "Muscat",
    region: "AS",
    currency: {
      code: "OMR",
      name: "Omani rial",
      symbol: "ر.ع.",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/om.png",
    dialling_code: "+968",
    isoCode: "512",
  },
  {
    name: "Pakistan",
    code: "PK",
    capital: "Islamabad",
    region: "AS",
    currency: {
      code: "PKR",
      name: "Pakistani rupee",
      symbol: "₨",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/pa.png",
    dialling_code: "+92",
    isoCode: "586",
  },
  {
    name: "Papua New Guinea",
    code: "PG",
    capital: "Port Moresby",
    region: "OC",
    currency: {
      code: "PGK",
      name: "Papua New Guinean kina",
      symbol: "K",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/pn.png",
    dialling_code: "+675",
    isoCode: "598",
  },
  {
    name: "Paraguay",
    code: "PY",
    capital: "Asunción",
    region: "SA",
    currency: {
      code: "PYG",
      name: "Paraguayan guaraní",
      symbol: "₲",
    },
    language: {
      code: "es",
      name: "Spanish",
    },
    flag: "https://flagcdn.com/h40/pr.png",
    dialling_code: "+595",
    isoCode: "600",
  },
  {
    name: "Peru",
    code: "PE",
    capital: "Lima",
    region: "SA",
    currency: {
      code: "PEN",
      name: "Peruvian sol",
      symbol: "S/.",
    },
    language: {
      code: "es",
      name: "Spanish",
    },
    flag: "https://flagcdn.com/h40/pe.png",
    dialling_code: "+51",
    isoCode: "604",
  },
  {
    name: "Philippines",
    code: "PH",
    capital: "Manila",
    region: "AS",
    currency: {
      code: "PHP",
      name: "Philippine peso",
      symbol: "₱",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/ph.png",
    dialling_code: "+63",
    isoCode: "608",
  },
  {
    name: "Poland",
    code: "PL",
    capital: "Warsaw",
    region: "EU",
    currency: {
      code: "PLN",
      name: "Polish złoty",
      symbol: "zł",
    },
    language: {
      code: "pl",
      name: "Polish",
    },
    flag: "https://flagcdn.com/h40/po.png",
    dialling_code: "+48",
    isoCode: "616",
  },
  {
    name: "Qatar",
    code: "QA",
    capital: "Doha",
    region: "AS",
    currency: {
      code: "QAR",
      name: "Qatari riyal",
      symbol: "ر.ق",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/qa.png",
    dialling_code: "+974",
    isoCode: "634",
  },
  {
    name: "Romania",
    code: "RO",
    capital: "Bucharest",
    region: "EU",
    currency: {
      code: "RON",
      name: "Romanian leu",
      symbol: "lei",
    },
    language: {
      code: "ro",
      name: "Romanian",
    },
    flag: "https://flagcdn.com/h40/ro.png",
    dialling_code: "+40",
    isoCode: "642",
  },
  {
    name: "Russian Federation",
    code: "RU",
    capital: "Moscow",
    region: "EU",
    currency: {
      code: "RUB",
      name: "Russian ruble",
      symbol: "₽",
    },
    language: {
      code: "ru",
      name: "Russian",
    },
    flag: "https://flagcdn.com/h40/ru.png",
    dialling_code: "+7",
    isoCode: "643",
  },
  {
    name: "Rwanda",
    code: "RW",
    capital: "Kigali",
    region: "AF",
    currency: {
      code: "RWF",
      name: "Rwandan franc",
      symbol: "Fr",
    },
    language: {
      code: "rw",
      name: "Kinyarwanda",
    },
    flag: "https://flagcdn.com/h40/rw.png",
    dialling_code: "+250",
    isoCode: "646",
  },
  {
    name: "Saint Helena, Ascension and Tristan da Cunha",
    code: "SH",
    capital: "Jamestown",
    region: "AF",
    currency: {
      code: "SHP",
      name: "Saint Helena pound",
      symbol: "£",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/sh.png",
    dialling_code: "+290",
    isoCode: "654",
  },
  {
    name: "Samoa",
    code: "WS",
    capital: "Apia",
    region: "OC",
    currency: {
      code: "WST",
      name: "Samoan tālā",
      symbol: "T",
    },
    language: {
      code: "sm",
      name: "Samoan",
    },
    flag: "https://flagcdn.com/h40/ws.png",
    dialling_code: "+685",
    isoCode: "882",
  },
  {
    name: "Sao Tome and Principe",
    code: "ST",
    capital: "São Tomé",
    region: "AF",
    currency: {
      code: "STD",
      name: "São Tomé and Príncipe dobra",
      symbol: "Db",
    },
    language: {
      code: "pt",
      name: "Portuguese",
    },
    flag: "https://flagcdn.com/h40/st.png",
    dialling_code: "+239",
    isoCode: "678",
  },
  {
    name: "Saudi Arabia",
    code: "SA",
    capital: "Riyadh",
    region: "AS",
    currency: {
      code: "SAR",
      name: "Saudi riyal",
      symbol: "ر.س",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/sa.png",
    dialling_code: "+966",
    isoCode: "682",
  },
  {
    name: "Serbia",
    code: "RS",
    capital: "Belgrade",
    region: "EU",
    currency: {
      code: "RSD",
      name: "Serbian dinar",
      symbol: "дин.",
    },
    language: {
      code: "sr",
      name: "Serbian",
    },
    flag: "https://flagcdn.com/h40/sr.png",
    dialling_code: "+381",
    isoCode: "688",
  },
  {
    name: "Seychelles",
    code: "SC",
    capital: "Victoria",
    region: "AF",
    currency: {
      code: "SCR",
      name: "Seychellois rupee",
      symbol: "₨",
    },
    language: {
      code: "fr",
      name: "French",
    },
    flag: "https://flagcdn.com/h40/sy.png",
    dialling_code: "+248",
    isoCode: "690",
  },
  {
    name: "Sierra Leone",
    code: "SL",
    capital: "Freetown",
    region: "AF",
    currency: {
      code: "SLL",
      name: "Sierra Leonean leone",
      symbol: "Le",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/sl.png",
    dialling_code: "+232",
    isoCode: "694",
  },
  {
    name: "Singapore",
    code: "SG",
    capital: "Singapore",
    region: "AS",
    currency: {
      code: "SGD",
      name: "Singapore dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/sg.png",
    dialling_code: "+65",
    isoCode: "702",
  },
  {
    name: "Solomon Islands",
    code: "SB",
    capital: "Honiara",
    region: "OC",
    currency: {
      code: "SBD",
      name: "Solomon Islands dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/sl.png",
    dialling_code: "+677",
    isoCode: "090",
  },
  {
    name: "Somalia",
    code: "SO",
    capital: "Mogadishu",
    region: "AF",
    currency: {
      code: "SOS",
      name: "Somali shilling",
      symbol: "Sh",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/so.png",
    dialling_code: "+252",
    isoCode: "706",
  },
  {
    name: "South Africa",
    code: "ZA",
    capital: "Pretoria",
    region: "AF",
    currency: {
      code: "ZAR",
      name: "South African rand",
      symbol: "R",
    },
    language: {
      code: "en",
      iso639_2: "eng",
      name: "English",
      nativeName: "English",
    },
    flag: "https://flagcdn.com/h40/za.png",
    dialling_code: "+27",
    isoCode: "710",
  },
  {
    name: "Korea (Republic of)",
    code: "KR",
    capital: "Seoul",
    region: "AS",
    currency: {
      code: "KRW",
      name: "South Korean won",
      symbol: "₩",
    },
    language: {
      code: "ko",
      name: "Korean",
    },
    flag: "https://flagcdn.com/h40/kr.png",
    dialling_code: "+82",
    isoCode: "410",
  },
  {
    name: "Sri Lanka",
    code: "LK",
    capital: "Colombo",
    region: "AS",
    currency: {
      code: "LKR",
      name: "Sri Lankan rupee",
      symbol: "Rs",
    },
    language: {
      code: "si",
      iso639_2: "sin",
      name: "Sinhalese",
      nativeName: "සිංහල",
    },
    flag: "https://flagcdn.com/h40/lk.png",
    dialling_code: "+94",
    isoCode: "144",
  },
  {
    name: "Sudan",
    code: "SD",
    capital: "Khartoum",
    region: "AF",
    currency: {
      code: "SDG",
      name: "Sudanese pound",
      symbol: "ج.س.",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/sd.png",
    dialling_code: "+249",
    isoCode: "729",
  },
  {
    name: "Suriname",
    code: "SR",
    capital: "Paramaribo",
    region: "SA",
    currency: {
      code: "SRD",
      name: "Surinamese dollar",
      symbol: "$",
    },
    language: {
      code: "nl",
      name: "Dutch",
    },
    flag: "https://flagcdn.com/h40/sr.png",
    dialling_code: "+597",
    isoCode: "740",
  },
  {
    name: "Swaziland",
    code: "SZ",
    capital: "Lobamba",
    region: "AF",
    currency: {
      code: "SZL",
      name: "Swazi lilangeni",
      symbol: "L",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/sw.png",
    dialling_code: "+268",
    isoCode: "748",
  },
  {
    name: "Sweden",
    code: "SE",
    capital: "Stockholm",
    region: "EU",
    currency: {
      code: "SEK",
      name: "Swedish krona",
      symbol: "kr",
    },
    language: {
      code: "sv",
      name: "Swedish",
    },
    flag: "https://flagcdn.com/h40/sw.png",
    dialling_code: "+46",
    isoCode: "752",
  },
  {
    name: "Syrian Arab Republic",
    code: "SY",
    capital: "Damascus",
    region: "AS",
    currency: {
      code: "SYP",
      name: "Syrian pound",
      symbol: "£",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/sy.png",
    dialling_code: "+963",
    isoCode: "760",
  },
  {
    name: "Taiwan",
    code: "TW",
    capital: "Taipei",
    region: "AS",
    currency: {
      code: "TWD",
      name: "New Taiwan dollar",
      symbol: "$",
    },
    language: {
      code: "zh",
      name: "Chinese",
    },
    flag: "https://flagcdn.com/h40/tw.png",
    dialling_code: "+886",
    isoCode: "158",
  },
  {
    name: "Tajikistan",
    code: "TJ",
    capital: "Dushanbe",
    region: "AS",
    currency: {
      code: "TJS",
      name: "Tajikistani somoni",
      symbol: "ЅМ",
    },
    language: {
      code: "tg",
      name: "Tajik",
    },
    flag: "https://flagcdn.com/h40/tj.png",
    dialling_code: "+992",
    isoCode: "762",
  },
  {
    name: "Tanzania, United Republic of",
    code: "TZ",
    capital: "Dodoma",
    region: "AF",
    currency: {
      code: "TZS",
      name: "Tanzanian shilling",
      symbol: "Sh",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/tz.png",
    dialling_code: "+255",
    isoCode: "834",
  },
  {
    name: "Thailand",
    code: "TH",
    capital: "Bangkok",
    region: "AS",
    currency: {
      code: "THB",
      name: "Thai baht",
      symbol: "฿",
    },
    language: {
      code: "th",
      name: "Thai",
    },
    flag: "https://flagcdn.com/h40/th.png",
    dialling_code: "+66",
    isoCode: "764",
  },
  {
    name: "Tonga",
    code: "TO",
    capital: "Nuku'alofa",
    region: "OC",
    currency: {
      code: "TOP",
      name: "Tongan paʻanga",
      symbol: "T$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/to.png",
    dialling_code: "+676",
    isoCode: "776",
  },
  {
    name: "Trinidad and Tobago",
    code: "TT",
    capital: "Port of Spain",
    region: "SA",
    currency: {
      code: "TTD",
      name: "Trinidad and Tobago dollar",
      symbol: "$",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/tt.png",
    dialling_code: "+1",
    isoCode: "780",
  },
  {
    name: "Tunisia",
    code: "TN",
    capital: "Tunis",
    region: "AF",
    currency: {
      code: "TND",
      name: "Tunisian dinar",
      symbol: "د.ت",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/tn.png",
    dialling_code: "+216",
    isoCode: "788",
  },
  {
    name: "Turkey",
    code: "TR",
    capital: "Ankara",
    region: "AS",
    currency: {
      code: "TRY",
      name: "Turkish lira",
      symbol: null,
    },
    language: {
      code: "tr",
      name: "Turkish",
    },
    flag: "https://flagcdn.com/h40/tu.png",
    dialling_code: "+90",
    isoCode: "792",
  },
  {
    name: "Turkmenistan",
    code: "TM",
    capital: "Ashgabat",
    region: "AS",
    currency: {
      code: "TMT",
      name: "Turkmenistan manat",
      symbol: "m",
    },
    language: {
      code: "tk",
      name: "Turkmen",
    },
    flag: "https://flagcdn.com/h40/tk.png",
    dialling_code: "+993",
    isoCode: "795",
  },
  {
    name: "Uganda",
    code: "UG",
    capital: "Kampala",
    region: "AF",
    currency: {
      code: "UGX",
      name: "Ugandan shilling",
      symbol: "Sh",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/ug.png",
    dialling_code: "+256",
    isoCode: "800",
  },
  {
    name: "Ukraine",
    code: "UA",
    capital: "Kiev",
    region: "EU",
    currency: {
      code: "UAH",
      name: "Ukrainian hryvnia",
      symbol: "₴",
    },
    language: {
      code: "uk",
      name: "Ukrainian",
    },
    flag: "https://flagcdn.com/h40/ua.png",
    dialling_code: "+380",
    isoCode: "804",
  },
  {
    name: "United Arab Emirates",
    code: "AE",
    capital: "Abu Dhabi",
    region: "AS",
    currency: {
      code: "AED",
      name: "United Arab Emirates dirham",
      symbol: "د.إ",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/ar.png",
    dialling_code: "+971",
    isoCode: "784",
  },
  {
    name: "United Kingdom of Great Britain and Northern Ireland",
    code: "GB",
    capital: "London",
    region: "EU",
    currency: {
      code: "GBP",
      name: "British pound",
      symbol: "£",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/gb.png",
    dialling_code: "+44",
    isoCode: "826",
  },
  {
    name: "Uruguay",
    code: "UY",
    capital: "Montevideo",
    region: "SA",
    currency: {
      code: "UYU",
      name: "Uruguayan peso",
      symbol: "$",
    },
    language: {
      code: "es",
      name: "Spanish",
    },
    flag: "https://flagcdn.com/h40/uy.png",
    dialling_code: "+598",
    isoCode: "858",
  },
  {
    name: "Uzbekistan",
    code: "UZ",
    capital: "Tashkent",
    region: "AS",
    currency: {
      code: "UZS",
      name: "Uzbekistani so'm",
      symbol: null,
    },
    language: {
      code: "uz",
      name: "Uzbek",
    },
    flag: "https://flagcdn.com/h40/uz.png",
    dialling_code: "+998",
    isoCode: "860",
  },
  {
    name: "Vanuatu",
    code: "VU",
    capital: "Port Vila",
    region: "OC",
    currency: {
      code: "VUV",
      name: "Vanuatu vatu",
      symbol: "Vt",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/vu.png",
    dialling_code: "+678",
    isoCode: "548",
  },
  {
    name: "Venezuela (Bolivarian Republic of)",
    code: "VE",
    capital: "Caracas",
    region: "SA",
    currency: {
      code: "VEF",
      name: "Venezuelan bolívar",
      symbol: "Bs F",
    },
    language: {
      code: "es",
      name: "Spanish",
    },
    flag: "https://flagcdn.com/h40/ve.png",
    dialling_code: "+58",
    isoCode: "862",
  },
  {
    name: "Viet Nam",
    code: "VN",
    capital: "Hanoi",
    region: "AS",
    currency: {
      code: "VND",
      name: "Vietnamese đồng",
      symbol: "₫",
    },
    language: {
      code: "vi",
      name: "Vietnamese",
    },
    flag: "https://flagcdn.com/h40/vn.png",
    dialling_code: "+84",
    isoCode: "704",
  },
  {
    name: "Yemen",
    code: "YE",
    capital: "Sana'a",
    region: "AS",
    currency: {
      code: "YER",
      name: "Yemeni rial",
      symbol: "﷼",
    },
    language: {
      code: "ar",
      name: "Arabic",
    },
    flag: "https://flagcdn.com/h40/ye.png",
    dialling_code: "+967",
    isoCode: "887",
  },
  {
    name: "Zambia",
    code: "ZM",
    capital: "Lusaka",
    region: "AF",
    currency: {
      code: "ZMW",
      name: "Zambian kwacha",
      symbol: "ZK",
    },
    language: {
      code: "en",
      name: "English",
    },
    flag: "https://flagcdn.com/h40/zm.png",
    dialling_code: "+260",
    isoCode: "894",
  },
];
